Repository apollographql/federation, pull requests merged in 2021-04, with the labels that each got.

#607 feat(gateway) Allow passing a function to `introspectionHeaders`
  docs/source/api/apollo-gateway.mdx
  gateway-js/CHANGELOG.md
  gateway-js/src/__tests__/integration/configuration.test.ts
  gateway-js/src/__tests__/integration/nockMocks.ts
  gateway-js/src/__tests__/loadServicesFromRemoteEndpoint.test.ts
  gateway-js/src/config.ts
  gateway-js/src/index.ts
  gateway-js/src/loadServicesFromRemoteEndpoint.ts
Labels: :hugs: improvement, ⛲️ feature

#658 chore(ci): Start running Rust tests on CircleCI
  .circleci/config.yml
  .github/actions-rs/grcov.yml
  .github/workflows/audit.yml
  .github/workflows/lint.yml
  .github/workflows/rust-test.yml
Labels: ⚡️ infra

#672 gateway(RemoteGraphQLDataSource): Only calculate hash for APQ when enabled
  gateway-js/CHANGELOG.md
  gateway-js/src/datasources/RemoteGraphQLDataSource.ts
Labels: :hugs: improvement
