Repository apollographql/federation, pull requests merged in 2021-07, with the labels that each got.

#848 chore(gateway): Update otel deps and rename tracer labels
  gateway-js/CHANGELOG.md
  gateway-js/package.json
  gateway-js/src/executeQueryPlan.ts
  gateway-js/src/index.ts
  gateway-js/src/utilities/opentelemetry.ts
  package-lock.json
Labels: :christmas_tree: dependencies

#849 fix(gateway): Fix TS error in OOB variables
  gateway-js/src/outOfBandReporter.ts
Labels: 🧬 typings

#859 fix(federation): Print @tag and @inaccessible directives conditionally
  federation-integration-testsuite-js/src/fixtures/index.ts
  federation-integration-testsuite-js/src/fixtures/special-cases/accountsWithoutTagOrInaccessible.ts
  federation-integration-testsuite-js/src/fixtures/special-cases/reviewsWithUpdate.ts
  federation-integration-testsuite-js/src/fixtures/special-cases/reviewsWithoutTagOrInaccessible.ts
  federation-js/src/composition/compose.ts
  federation-js/src/composition/utils.ts
  federation-js/src/service/__tests__/printSupergraphSdl.test.ts
  federation-js/src/service/printSupergraphSdl.ts
  gateway-js/src/__tests__/loadSupergraphSdlFromStorage.test.ts
  harmonizer/src/snapshots/harmonizer__tests__it_works.snap
  query-planner-js/src/composedSchema/buildComposedSchema.ts
Labels: ⛲️ feature

#766 Release @apollo/federation@0.26.0
  federation-integration-testsuite-js/package.json
  federation-integration-testsuite-js/src/fixtures/accounts.ts
  federation-integration-testsuite-js/src/fixtures/index.ts
  federation-integration-testsuite-js/src/fixtures/reviews.ts
  federation-integration-testsuite-js/src/fixtures/special-cases/accountsWithoutTagOrInaccessible.ts
  federation-integration-testsuite-js/src/fixtures/special-cases/reviewsWithUpdate.ts
  federation-integration-testsuite-js/src/fixtures/special-cases/reviewsWithoutTagOrInaccessible.ts
  federation-js/CHANGELOG.md
  federation-js/package.json
  federation-js/src/composition/compose.ts
  federation-js/src/composition/normalize.ts
  federation-js/src/composition/types.ts
  federation-js/src/composition/utils.ts
  federation-js/src/composition/validate/postComposition/executableDirectivesIdentical.ts
  federation-js/src/composition/validate/postComposition/executableDirectivesInAllServices.ts
  federation-js/src/composition/validate/preComposition/keyFieldsMissingExternal.ts
  federation-js/src/composition/validate/sdl/__tests__/matchingEnums.test.ts
  federation-js/src/composition/validate/sdl/__tests__/matchingUnions.test.ts
  federation-js/src/composition/validate/sdl/__tests__/possibleTypeExtensions.test.ts
  federation-js/src/composition/validate/sdl/__tests__/uniqueFieldDefinitionNames.test.ts
  federation-js/src/composition/validate/sdl/__tests__/uniqueTypeNamesWithFields.test.ts
  federation-js/src/directives.ts
  federation-js/src/service/__tests__/printFederatedSchema.test.ts
  federation-js/src/service/__tests__/printSupergraphSdl.test.ts
  federation-js/src/service/buildFederatedSchema.ts
  federation-js/src/service/printFederatedSchema.ts
  federation-js/src/service/printSupergraphSdl.ts
  gateway-js/CHANGELOG.md
  gateway-js/package.json
  gateway-js/src/__tests__/integration/value-types.test.ts
  gateway-js/src/__tests__/loadSupergraphSdlFromStorage.test.ts
  harmonizer/package.json
  query-planner-js/CHANGELOG.md
  query-planner-js/package.json
  query-planner-js/src/composedSchema/buildComposedSchema.ts
  query-planner-js/src/composedSchema/metadata.ts
Labels: :label: release

#863 Release 'harmonizer' crate v0.26.0
  Cargo.lock
  harmonizer/Cargo.toml
  harmonizer/package.json
  package-lock.json
Labels: :label: release

#868 fix(federation): Skip missing types while iterating over field directive usages
  federation-js/CHANGELOG.md
  federation-js/src/composition/__tests__/composeAndValidate.test.ts
  federation-js/src/composition/compose.ts
Labels: :beetle: bug

#881 feat(gateway): Default to Uplink for composed supergraph managed federation
  gateway-js/CHANGELOG.md
  gateway-js/src/__tests__/integration/configuration.test.ts
  gateway-js/src/__tests__/integration/legacyNetworkRequests.test.ts
  gateway-js/src/__tests__/integration/networkRequests.test.ts
  gateway-js/src/config.ts
  gateway-js/src/index.ts
Labels: ⛲️ feature

#894 fix(gateway): Move loadStatic toAPISchema call into try/catch block
  gateway-js/CHANGELOG.md
  gateway-js/src/index.ts
Labels: :pear: error-handling

#893 fix(gateway): Prevent inaccessible type names from being leaked in error messages
  federation-integration-testsuite-js/src/fixtures/special-cases/supergraphWithInaccessible.ts
  gateway-js/src/__tests__/executeQueryPlan.test.ts
  gateway-js/src/executeQueryPlan.ts
  gateway-js/src/utilities/__tests__/cleanErrorOfInaccessibleElements.test.ts
  gateway-js/src/utilities/cleanErrorOfInaccessibleNames.ts
  query-planner-js/CHANGELOG.md
  query-planner-js/src/composedSchema/removeInaccessibleElements.ts
  query-planner-js/src/composedSchema/toAPISchema.ts
Labels: :hugs: improvement

#899 docs: rm instruction to set `APOLLO_SCHEMA_CONFIG_DELIVERY_ENDPOINT` for Uplink
  docs/source/managed-federation/setup.mdx
  docs/source/quickstart-pt-2.mdx
Labels: size - S

#900 fix(gateway): Remove `path`, `query` and `variables` field from subgraph error responses
  gateway-js/CHANGELOG.md
  gateway-js/src/__tests__/executeQueryPlan.test.ts
  gateway-js/src/executeQueryPlan.ts
Labels: :hugs: improvement

#892 Release @apollo/gateway@0.34.0
  Cargo.lock
  docs/source/errors.md
  docs/source/managed-federation/setup.mdx
  docs/source/quickstart-pt-2.mdx
  federation-integration-testsuite-js/package.json
  federation-integration-testsuite-js/src/fixtures/accounts.ts
  federation-integration-testsuite-js/src/fixtures/index.ts
  federation-integration-testsuite-js/src/fixtures/reviews.ts
  federation-integration-testsuite-js/src/fixtures/special-cases/supergraphWithInaccessible.ts
  federation-js/CHANGELOG.md
  federation-js/package.json
  federation-js/src/composition/__tests__/composeAndValidate.test.ts
  federation-js/src/composition/utils.ts
  federation-js/src/composition/validate/preNormalization/__tests__/tagDirective.test.ts
  federation-js/src/composition/validate/preNormalization/index.ts
  federation-js/src/composition/validate/preNormalization/tagDirective.ts
  federation-js/src/service/buildFederatedSchema.ts
  gateway-js/CHANGELOG.md
  gateway-js/package.json
  gateway-js/src/__tests__/executeQueryPlan.test.ts
  gateway-js/src/__tests__/execution-utils.ts
  gateway-js/src/__tests__/gateway/composedSdl.test.ts
  gateway-js/src/__tests__/gateway/executor.test.ts
  gateway-js/src/__tests__/integration/configuration.test.ts
  gateway-js/src/__tests__/integration/legacyNetworkRequests.test.ts
  gateway-js/src/__tests__/integration/networkRequests.test.ts
  gateway-js/src/config.ts
  gateway-js/src/executeQueryPlan.ts
  gateway-js/src/index.ts
  gateway-js/src/utilities/__tests__/cleanErrorOfInaccessibleElements.test.ts
  gateway-js/src/utilities/cleanErrorOfInaccessibleNames.ts
  harmonizer/Cargo.toml
  harmonizer/package.json
  package-lock.json
  package.json
  query-planner-js/CHANGELOG.md
  query-planner-js/package.json
  query-planner-js/src/composedSchema/__tests__/removeInaccessibleElements.test.ts
  query-planner-js/src/composedSchema/__tests__/toAPISchema.test.ts
  query-planner-js/src/composedSchema/buildComposedSchema.ts
  query-planner-js/src/composedSchema/core.ts
  query-planner-js/src/composedSchema/index.ts
  query-planner-js/src/composedSchema/removeInaccessibleElements.ts
  query-planner-js/src/composedSchema/toAPISchema.ts
Labels: :label: release

#911 chore(gateway): Remove server + types alpha versions
  gateway-js/package.json
  package-lock.json
Labels: :christmas_tree: dependencies

#903 Release @apollo/gateway@0.35.0
  gateway-js/CHANGELOG.md
  gateway-js/package.json
  gateway-js/src/index.ts
  harmonizer/package.json
  package-lock.json
Labels: :label: release

#913 fix(deps): Narrow `graphql` peerDependencies to versions that actually work
  federation-js/CHANGELOG.md
  federation-js/package.json
  gateway-js/CHANGELOG.md
  gateway-js/package.json
  package-lock.json
  query-planner-js/CHANGELOG.md
  query-planner-js/package.json
Labels: 2021-07, :christmas_tree: dependencies
