Repository apollographql/federation, pull requests merged in 2021-03, with the labels that each got.

#551 Replaces `sku` field by `upc`
  docs/source/federation-spec.md
Labels: :hugs: improvement, :memo: documentation

#539 fix(gateway): Make `protected` fields and methods `private` (except `loadServiceDefinitions`)
  gateway-js/CHANGELOG.md
  gateway-js/src/index.ts
Labels: :hugs: improvement, 🧬 typings

#270 feat(pkg): build esm and cjs mods
  gateway-js/CHANGELOG.md
  query-planner-wasm/CHANGELOG.md
  query-planner-wasm/package-lock.json
  query-planner-wasm/package.json
Labels: ⛲️ feature

#458 feat(gateway): Update managed federation to fetch "cloud config"
  .circleci/config.yml
  codegen.yml
  federation-integration-testsuite-js/src/fixtures/index.ts
  federation-integration-testsuite-js/src/fixtures/reviewsWithUpdate.ts
  gateway-js/src/__generated__/graphqlTypes.ts
  gateway-js/src/__tests__/execution-utils.ts
  gateway-js/src/__tests__/gateway/executor.test.ts
  gateway-js/src/__tests__/integration/configuration.test.ts
  gateway-js/src/__tests__/integration/legacyNetworkRequests.test.ts
  gateway-js/src/__tests__/integration/legacyNockMocks.ts
  gateway-js/src/__tests__/integration/logger.test.ts
  gateway-js/src/__tests__/integration/networkRequests.test.ts
  gateway-js/src/__tests__/integration/nockMocks.ts
  gateway-js/src/__tests__/loadCsdlFromStorage.test.ts
  gateway-js/src/config.ts
  gateway-js/src/index.ts
  gateway-js/src/legacyLoadServicesFromStorage.ts
  gateway-js/src/loadCsdlFromStorage.ts
  gateway-js/src/loadServicesFromRemoteEndpoint.ts
  package-lock.json
  package.json
  query-planner/src/helpers.rs
Labels: :hugs: improvement, ⚡️ infra

#585 fix(gateway): Address typings issue for `getDefaultFetcher`
  gateway-js/CHANGELOG.md
  gateway-js/src/index.ts
Labels: 🧬 typings

#600 feat(gateway): Provide `context` to `didEncounterError` for RGDS
  gateway-js/CHANGELOG.md
  gateway-js/src/datasources/RemoteGraphQLDataSource.ts
  gateway-js/src/datasources/__tests__/RemoteGraphQLDataSource.test.ts
Labels: :hugs: improvement
