Repository apollographql/federation, pull requests merged in 2021-06, with the labels that each got.

#777 feat(gateway): Submit out of band error reporters when supergraph requests fail
  codegen.yml
  gateway-js/CHANGELOG.md
  gateway-js/src/__generated__/graphqlTypes.ts
  gateway-js/src/__tests__/integration/nockMocks.ts
  gateway-js/src/__tests__/loadSupergraphSdlFromStorage.test.ts
  gateway-js/src/loadSupergraphSdlFromStorage.ts
  gateway-js/src/outOfBandReporter.ts
Labels: :pear: error-handling, ⛲️ feature

#824 feat(federation): Deterministically sort composed schema
  federation-js/CHANGELOG.md
  federation-js/src/composition/__tests__/compose.test.ts
  federation-js/src/composition/__tests__/composeAndValidate.test.ts
  federation-js/src/composition/compose.ts
  federation-js/src/service/__tests__/printFederatedSchema.test.ts
  federation-js/src/service/__tests__/printSupergraphSdl.test.ts
  gateway-js/src/__tests__/integration/configuration.test.ts
  gateway-js/src/__tests__/integration/custom-directives.test.ts
  gateway-js/src/__tests__/loadSupergraphSdlFromStorage.test.ts
  harmonizer/src/snapshots/harmonizer__tests__it_works.snap
Labels: :hugs: improvement, ⛲️ feature

#834 fix(federation): Preserve all @tags
  federation-integration-testsuite-js/src/fixtures/accounts.ts
  federation-integration-testsuite-js/src/fixtures/reviews.ts
  federation-js/src/composition/compose.ts
  federation-js/src/composition/normalize.ts
  federation-js/src/composition/utils.ts
  federation-js/src/composition/validate/postComposition/executableDirectivesIdentical.ts
  federation-js/src/composition/validate/postComposition/executableDirectivesInAllServices.ts
  federation-js/src/composition/validate/preComposition/keyFieldsMissingExternal.ts
  federation-js/src/composition/validate/sdl/__tests__/matchingEnums.test.ts
  federation-js/src/composition/validate/sdl/__tests__/matchingUnions.test.ts
  federation-js/src/composition/validate/sdl/__tests__/possibleTypeExtensions.test.ts
  federation-js/src/composition/validate/sdl/__tests__/uniqueFieldDefinitionNames.test.ts
  federation-js/src/composition/validate/sdl/__tests__/uniqueTypeNamesWithFields.test.ts
  federation-js/src/directives.ts
  federation-js/src/service/__tests__/printFederatedSchema.test.ts
  federation-js/src/service/__tests__/printSupergraphSdl.test.ts
  federation-js/src/service/buildFederatedSchema.ts
  federation-js/src/service/printFederatedSchema.ts
  federation-js/src/service/printSupergraphSdl.ts
  gateway-js/src/__tests__/loadSupergraphSdlFromStorage.test.ts
Labels: :beetle: bug

#845 Release @apollo/gateway@0.31.0
  docs/gatsby-config.js
  docs/source/metrics.md
  docs/source/opentelemetry.mdx
  federation-integration-testsuite-js/package.json
  federation-integration-testsuite-js/src/snapshotSerializers/index.ts
  federation-integration-testsuite-js/src/snapshotSerializers/readableSpanArraySerializer.ts
  gateway-js/CHANGELOG.md
  gateway-js/package.json
  gateway-js/src/__tests__/gateway/__snapshots__/opentelemetry.test.ts.snap
  gateway-js/src/__tests__/gateway/opentelemetry.test.ts
  gateway-js/src/executeQueryPlan.ts
  gateway-js/src/index.ts
  gateway-js/src/utilities/opentelemetry.ts
  harmonizer/package.json
  package.json
Labels: :label: release
