Repository apollographql/federation, pull requests merged in 2021-12, with the labels that each got.

#1286 chore(infra): Update prompt to include 'git add' recommendation
  prompt-update-changelogs.js
Labels: ⚡️ infra

#1284 RemoteGraphQLDataSource uses `make-fetch-happen` by default
  gateway-js/CHANGELOG.md
  gateway-js/src/__mocks__/make-fetch-happen-fetcher.ts
  gateway-js/src/__tests__/gateway/buildService.test.ts
  gateway-js/src/__tests__/gateway/composedSdl.test.ts
  gateway-js/src/__tests__/gateway/executor.test.ts
  gateway-js/src/datasources/RemoteGraphQLDataSource.ts
  gateway-js/src/datasources/__tests__/RemoteGraphQLDataSource.test.ts
Labels: component/gateway runtime, 2021-12

#1236 Release @apollo/gateway@0.45.0
  Cargo.lock
  federation-integration-testsuite-js/package.json
  gateway-js/CHANGELOG.md
  gateway-js/package.json
  gateway-js/src/__tests__/integration/configuration.test.ts
  gateway-js/src/__tests__/integration/legacyNetworkRequests.test.ts
  gateway-js/src/__tests__/integration/legacyNockMocks.ts
  gateway-js/src/__tests__/integration/networkRequests.test.ts
  gateway-js/src/__tests__/integration/nockMocks.ts
  gateway-js/src/__tests__/loadSupergraphSdlFromStorage.test.ts
  gateway-js/src/config.ts
  gateway-js/src/index.ts
  gateway-js/src/legacyLoadServicesFromStorage.ts
  gateway-js/src/loadSupergraphSdlFromStorage.ts
  harmonizer/Cargo.toml
  harmonizer/package.json
  package-lock.json
  query-planner-js/CHANGELOG.md
  query-planner-js/package.json
  router-bridge/package.json
Labels: :label: release
