Repository apollographql/federation, pull requests merged in 2021-08, with the labels that each got.

#947 Release @apollo/gateway@0.37.0
  gateway-js/CHANGELOG.md
  gateway-js/package.json
  gateway-js/src/__tests__/gateway/__snapshots__/opentelemetry.test.ts.snap
  gateway-js/src/__tests__/gateway/opentelemetry.test.ts
  gateway-js/src/index.ts
  package-lock.json
Labels: :label: release

#915 chore(federation): Rename `buildFederatedSchema` -> `buildSubgraphSchema`
  docs/source/api/apollo-federation.mdx
  docs/source/migrating-from-stitching.md
  docs/source/quickstart-pt-3.mdx
  docs/source/subgraphs.mdx
  federation-js/CHANGELOG.md
  federation-js/README.md
  federation-js/src/service/__tests__/buildSubgraphSchema.test.ts
  federation-js/src/service/buildSubgraphSchema.ts
  federation-js/src/service/index.ts
  gateway-js/src/__tests__/execution-utils.ts
  gateway-js/src/__tests__/gateway/opentelemetry.test.ts
  gateway-js/src/__tests__/gateway/queryPlanCache.test.ts
  gateway-js/src/__tests__/gateway/reporting.test.ts
  gateway-js/src/__tests__/integration/aliases.test.ts
  gateway-js/src/datasources/__tests__/LocalGraphQLDataSource.test.ts
Labels: :memo: documentation, :hugs: improvement, motivation/ergonomics, size/small, 2021-08

#945 feat(federation): @tag support for Object, Interface, and Union types
  docs/source/errors.md
  federation-integration-testsuite-js/src/fixtures/accounts.ts
  federation-integration-testsuite-js/src/fixtures/reviews.ts
  federation-js/CHANGELOG.md
  federation-js/src/composition/DirectiveMetadata.ts
  federation-js/src/composition/__tests__/compose.test.ts
  federation-js/src/composition/__tests__/composeAndValidate.test.ts
  federation-js/src/composition/compose.ts
  federation-js/src/composition/types.ts
  federation-js/src/composition/validate/preNormalization/__tests__/tagDirective.test.ts
  federation-js/src/composition/validate/preNormalization/tagDirective.ts
  federation-js/src/directives.ts
  federation-js/src/service/__tests__/printFederatedSchema.test.ts
  federation-js/src/service/__tests__/printSupergraphSdl.test.ts
  federation-js/src/service/printFederatedSchema.ts
  federation-js/src/service/printSupergraphSdl.ts
  gateway-js/src/__tests__/loadSupergraphSdlFromStorage.test.ts
  query-planner-js/src/composedSchema/metadata.ts
Labels: 🍳 breaking-change, component/composition, 2021-08

#953 Release @apollo/federation@0.29.0
  docs/source/errors.md
  federation-integration-testsuite-js/package.json
  federation-integration-testsuite-js/src/fixtures/accounts.ts
  federation-integration-testsuite-js/src/fixtures/reviews.ts
  federation-js/CHANGELOG.md
  federation-js/package.json
  federation-js/src/composition/DirectiveMetadata.ts
  federation-js/src/composition/__tests__/compose.test.ts
  federation-js/src/composition/__tests__/composeAndValidate.test.ts
  federation-js/src/composition/compose.ts
  federation-js/src/composition/types.ts
  federation-js/src/composition/validate/preNormalization/__tests__/tagDirective.test.ts
  federation-js/src/composition/validate/preNormalization/tagDirective.ts
  federation-js/src/directives.ts
  federation-js/src/service/__tests__/printFederatedSchema.test.ts
  federation-js/src/service/__tests__/printSupergraphSdl.test.ts
  federation-js/src/service/printFederatedSchema.ts
  federation-js/src/service/printSupergraphSdl.ts
  gateway-js/package.json
  gateway-js/src/__tests__/loadSupergraphSdlFromStorage.test.ts
  harmonizer/Cargo.toml
  package-lock.json
  query-planner-js/package.json
  query-planner-js/src/composedSchema/metadata.ts
Labels: :label: release, 2021-08

#957 feat(gateway): Implement @core v0.2, including "for" and core__Purpose support
  Cargo.lock
  docs/source/index.mdx
  docs/source/quickstart.mdx
  federation-integration-testsuite-js/src/fixtures/special-cases/supergraphWithInaccessible.ts
  federation-integration-testsuite-js/src/snapshotSerializers/graphqlErrorSerializer.ts
  federation-js/src/coreSpec.ts
  federation-js/src/service/__tests__/printSupergraphSdl.test.ts
  federation-js/src/service/printSupergraphSdl.ts
  gateway-js/CHANGELOG.md
  gateway-js/package.json
  gateway-js/src/__tests__/loadSupergraphSdlFromStorage.test.ts
  gateway-js/src/core/__tests__/core.test.ts
  gateway-js/src/core/index.ts
  gateway-js/src/index.ts
  gateway-js/src/utilities/__tests__/cleanErrorOfInaccessibleElements.test.ts
  harmonizer/src/snapshots/harmonizer__tests__it_works.snap
  package-lock.json
  query-planner-js/src/__tests__/features/basic/supergraphSdl.graphql
  query-planner-js/src/__tests__/features/multiple-keys/supergraphSdl.graphql
  query-planner-js/src/composedSchema/__tests__/removeInaccessibleElements.test.ts
  query-planner-js/src/composedSchema/buildComposedSchema.ts
Labels: component/gateway runtime, size/medium, 2021-08
