Repository apollographql/federation, pull requests merged in 2022-02, with the labels that each got.

#1463 fix(subgraph): Conditionally print @specifiedBy directive on scalars correctly
  subgraph-js/CHANGELOG.md
  subgraph-js/src/__tests__/printSubgraphSchema.test.ts
  subgraph-js/src/printSubgraphSchema.ts
Labels: ↪️ backport-to-0.x

#1458 Add Hot Chocolate to the subgraph-compatible libraries table
  docs/source/other-servers.md
Labels: :memo: documentation

#1460 Add Hot Chocolate to the subgraph-compatible libraries table
  docs/source/other-servers.md
Labels: :memo: documentation

#1472 chore(deps): Remove `graphql@15` from peer dependencies
  composition-js/CHANGELOG.md
  composition-js/package.json
  gateway-js/CHANGELOG.md
  gateway-js/package.json
  harmonizer/package.json
  internals-js/CHANGELOG.md
  internals-js/package.json
  package-lock.json
  package.json
  query-graphs-js/CHANGELOG.md
  query-graphs-js/package.json
  query-planner-js/package.json
  subgraph-js/CHANGELOG.md
  subgraph-js/package.json
Labels: :christmas_tree: dependencies

#1476 Release `@apollo/gateway@0.47.0`
  Cargo.lock
  federation-integration-testsuite-js/package.json
  federation-js/CHANGELOG.md
  federation-js/package.json
  gateway-js/CHANGELOG.md
  gateway-js/package.json
  harmonizer/Cargo.toml
  harmonizer/package.json
  package-lock.json
  query-planner-js/CHANGELOG.md
  query-planner-js/package.json
  router-bridge/package.json
  subgraph-js/CHANGELOG.md
  subgraph-js/package.json
Labels: :label: release

#1477 Release @apollo/composition@2.0.0-alpha.5, @apollo/gateway@2.0.0-alpha.5, @apollo/federation-internals@2.0.0-alpha.5, @apollo/query-graphs@2.0.0-alpha.5, @apollo/query-planner@2.0.0-alpha.5, @apollo/subgraph@2.0.0-alpha.4
  Cargo.lock
  composition-js/CHANGELOG.md
  composition-js/package.json
  gateway-js/CHANGELOG.md
  gateway-js/package.json
  harmonizer/Cargo.toml
  harmonizer/package.json
  internals-js/CHANGELOG.md
  internals-js/package.json
  package-lock.json
  query-graphs-js/CHANGELOG.md
  query-graphs-js/package.json
  query-planner-js/CHANGELOG.md
  query-planner-js/package.json
  router-bridge/package.json
  subgraph-js/CHANGELOG.md
  subgraph-js/package.json
Labels: :label: release

#1473 Create specific error class to signal uplink fetcher errors
  gateway-js/CHANGELOG.md
  gateway-js/src/index.ts
  gateway-js/src/supergraphManagers/UplinkFetcher/__tests__/loadSupergraphSdlFromStorage.test.ts
  gateway-js/src/supergraphManagers/UplinkFetcher/loadSupergraphSdlFromStorage.ts
  gateway-js/src/supergraphManagers/index.ts
Labels: ↪️ backport-to-0.x

#1491 Release `@apollo/gateway@0.48.0`
  Cargo.lock
  federation-integration-testsuite-js/package.json
  federation-js/CHANGELOG.md
  federation-js/package.json
  gateway-js/CHANGELOG.md
  gateway-js/package.json
  harmonizer/Cargo.toml
  harmonizer/package.json
  package-lock.json
  query-planner-js/CHANGELOG.md
  query-planner-js/package.json
  router-bridge/package.json
  subgraph-js/CHANGELOG.md
  subgraph-js/package.json
Labels: :label: release

#1499 fix(subgraph): Fix `GraphQLResolverMap` types - allow `args` fields to be typed by users
  federation-integration-testsuite-js/src/resolverMap.ts
  gateway-js/CHANGELOG.md
  gateway-js/src/schema-helper/resolverMap.ts
  subgraph-js/CHANGELOG.md
  subgraph-js/src/schema-helper/resolverMap.ts
Labels: 🧬 typings

#1503 fix(gateway): Resolve gateway retry issues (`UplinkFetcher failed to update...`) (`version-0.x`)
  docs/source/api/apollo-gateway.mdx
  gateway-js/CHANGELOG.md
  gateway-js/package.json
  gateway-js/src/__tests__/integration/nockMocks.ts
  gateway-js/src/index.ts
  gateway-js/src/supergraphManagers/LegacyFetcher/index.ts
  gateway-js/src/supergraphManagers/LocalCompose/index.ts
  gateway-js/src/supergraphManagers/UplinkFetcher/__tests__/loadSupergraphSdlFromStorage.test.ts
  gateway-js/src/supergraphManagers/UplinkFetcher/index.ts
  gateway-js/src/supergraphManagers/UplinkFetcher/loadSupergraphSdlFromStorage.ts
  package-lock.json
  package.json
Labels: ↪️ port-to-2.x

#1505 Release `@apollo/gateway@0.48.1`
  Cargo.lock
  federation-integration-testsuite-js/package.json
  federation-js/CHANGELOG.md
  federation-js/package.json
  gateway-js/CHANGELOG.md
  gateway-js/package.json
  harmonizer/Cargo.toml
  harmonizer/package.json
  package-lock.json
  subgraph-js/CHANGELOG.md
  subgraph-js/package.json
Labels: :label: release

#1531 Update Apollo Gateway readme usage with Introspect and Compose
  gateway-js/README.md
Labels: ↪️ backport-to-0.x
