Repository apollographql/federation, pull requests merged in 2022-01, with the labels that each got.

#1363 Release @apollo/gateway@2.0.0-alpha.3, @apollo/composition@2.0.0-alpha.3, @apollo/query-planner@2.0.0-alpha.3, @apollo/query-graphs@2.0.0-alpha.3, @apollo/federation-internals@2.0.0-alpha.3.
  Cargo.lock
  composition-js/CHANGELOG.md
  composition-js/package.json
  gateway-js/CHANGELOG.md
  gateway-js/package.json
  harmonizer/Cargo.toml
  harmonizer/package.json
  internals-js/CHANGELOG.md
  internals-js/package.json
  package-lock.json
  query-graphs-js/CHANGELOG.md
  query-graphs-js/package.json
  query-planner-js/CHANGELOG.md
  query-planner-js/package.json
  router-bridge/package.json
  subgraph-js/CHANGELOG.md
Labels: :label: release, 2022-01

#1365 Release @apollo/gateway@0.45.1
  Cargo.lock
  gateway-js/CHANGELOG.md
  gateway-js/package.json
  harmonizer/Cargo.toml
  harmonizer/package.json
  package-lock.json
  router-bridge/package.json
Labels: :label: release, 2022-01

#1246 feat(gateway): Implement new `supergraphSdl()` config option for dynamic gateway updates
  codegen.yml
  docs/source/api/apollo-gateway.mdx
  docs/source/entities.mdx
  docs/source/gateway.mdx
  docs/source/managed-federation/uplink.mdx
  docs/source/subgraphs.mdx
  federation-integration-testsuite-js/src/fixtures/index.ts
  federation-js/src/__tests__/joinSpec.test.ts
  gateway-js/CHANGELOG.md
  gateway-js/package.json
  gateway-js/src/__tests__/execution-utils.ts
  gateway-js/src/__tests__/gateway/buildService.test.ts
  gateway-js/src/__tests__/gateway/composedSdl.test.ts
  gateway-js/src/__tests__/gateway/lifecycle-hooks.test.ts
  gateway-js/src/__tests__/gateway/opentelemetry.test.ts
  gateway-js/src/__tests__/gateway/queryPlanCache.test.ts
  gateway-js/src/__tests__/gateway/reporting.test.ts
  gateway-js/src/__tests__/gateway/supergraphSdl.test.ts
  gateway-js/src/__tests__/integration/aliases.test.ts
  gateway-js/src/__tests__/integration/configuration.test.ts
  gateway-js/src/__tests__/integration/logger.test.ts
  gateway-js/src/__tests__/integration/networkRequests.test.ts
  gateway-js/src/__tests__/integration/nockMocks.ts
  gateway-js/src/config.ts
  gateway-js/src/index.ts
  gateway-js/src/supergraphManagers/IntrospectAndCompose/__tests__/IntrospectAndCompose.test.ts
  gateway-js/src/supergraphManagers/IntrospectAndCompose/__tests__/loadServicesFromRemoteEndpoint.test.ts
  gateway-js/src/supergraphManagers/IntrospectAndCompose/__tests__/tsconfig.json
  gateway-js/src/supergraphManagers/IntrospectAndCompose/index.ts
  gateway-js/src/supergraphManagers/IntrospectAndCompose/loadServicesFromRemoteEndpoint.ts
  gateway-js/src/supergraphManagers/LegacyFetcher/index.ts
  gateway-js/src/supergraphManagers/LocalCompose/index.ts
  gateway-js/src/supergraphManagers/UplinkFetcher/__tests__/loadSupergraphSdlFromStorage.test.ts
  gateway-js/src/supergraphManagers/UplinkFetcher/__tests__/tsconfig.json
  gateway-js/src/supergraphManagers/UplinkFetcher/index.ts
  gateway-js/src/supergraphManagers/UplinkFetcher/loadSupergraphSdlFromStorage.ts
  gateway-js/src/supergraphManagers/UplinkFetcher/outOfBandReporter.ts
  gateway-js/src/supergraphManagers/index.ts
  gateway-js/src/utilities/createHash.ts
  gateway-js/src/utilities/isNodeLike.ts
  package-lock.json
  package.json
Labels: component/gateway runtime, size/large, 2022-01, ↪️ port-to-2.x

#1373 chore(infra): Enable codesandbox CI (`main`)
  .codesandbox/ci.json
Labels: ⚡️ infra

#1372 chore(infra): Enable codesandbox CI (version-0.x)
  .codesandbox/ci.json
Labels: ⚡️ infra

#1369 Release @apollo/gateway@0.46.0
  Cargo.lock
  codegen.yml
  docs/source/api/apollo-gateway.mdx
  docs/source/entities.mdx
  docs/source/gateway.mdx
  docs/source/managed-federation/uplink.mdx
  docs/source/subgraphs.mdx
  federation-integration-testsuite-js/package.json
  federation-integration-testsuite-js/src/fixtures/index.ts
  federation-integration-testsuite-js/src/matchers/utils.ts
  federation-js/CHANGELOG.md
  federation-js/package.json
  federation-js/src/__tests__/joinSpec.test.ts
  gateway-js/CHANGELOG.md
  gateway-js/package.json
  gateway-js/src/__tests__/execution-utils.ts
  gateway-js/src/__tests__/gateway/buildService.test.ts
  gateway-js/src/__tests__/gateway/composedSdl.test.ts
  gateway-js/src/__tests__/gateway/lifecycle-hooks.test.ts
  gateway-js/src/__tests__/gateway/opentelemetry.test.ts
  gateway-js/src/__tests__/gateway/queryPlanCache.test.ts
  gateway-js/src/__tests__/gateway/reporting.test.ts
  gateway-js/src/__tests__/gateway/supergraphSdl.test.ts
  gateway-js/src/__tests__/integration/aliases.test.ts
  gateway-js/src/__tests__/integration/configuration.test.ts
  gateway-js/src/__tests__/integration/logger.test.ts
  gateway-js/src/__tests__/integration/networkRequests.test.ts
  gateway-js/src/__tests__/integration/nockMocks.ts
  gateway-js/src/config.ts
  gateway-js/src/index.ts
  gateway-js/src/supergraphManagers/IntrospectAndCompose/__tests__/IntrospectAndCompose.test.ts
  gateway-js/src/supergraphManagers/IntrospectAndCompose/__tests__/loadServicesFromRemoteEndpoint.test.ts
  gateway-js/src/supergraphManagers/IntrospectAndCompose/__tests__/tsconfig.json
  gateway-js/src/supergraphManagers/IntrospectAndCompose/index.ts
  gateway-js/src/supergraphManagers/IntrospectAndCompose/loadServicesFromRemoteEndpoint.ts
  gateway-js/src/supergraphManagers/LegacyFetcher/index.ts
  gateway-js/src/supergraphManagers/LocalCompose/index.ts
  gateway-js/src/supergraphManagers/UplinkFetcher/__tests__/loadSupergraphSdlFromStorage.test.ts
  gateway-js/src/supergraphManagers/UplinkFetcher/__tests__/tsconfig.json
  gateway-js/src/supergraphManagers/UplinkFetcher/index.ts
  gateway-js/src/supergraphManagers/UplinkFetcher/loadSupergraphSdlFromStorage.ts
  gateway-js/src/supergraphManagers/UplinkFetcher/outOfBandReporter.ts
  gateway-js/src/supergraphManagers/index.ts
  gateway-js/src/utilities/createHash.ts
  gateway-js/src/utilities/isNodeLike.ts
  harmonizer/Cargo.toml
  harmonizer/package.json
  package-lock.json
  package.json
  query-planner-js/CHANGELOG.md
  query-planner-js/package.json
  router-bridge/package.json
Labels: :label: release, 2022-01

#1391 chore(deps): Add missing `deep-equal` dependency
  package-lock.json
  query-graphs-js/package.json
Labels: :christmas_tree: dependencies

#1392 Release @apollo/composition@2.0.0-alpha.4, @apollo/gateway@2.0.0-alpha.4, @apollo/federation-internals@2.0.0-alpha.4, @apollo/query-graphs@2.0.0-alpha.4, @apollo/query-planner@2.0.0-alpha.4, @apollo/subgraph@2.0.0-alpha.3
  Cargo.lock
  composition-js/package.json
  federation-integration-testsuite-js/package.json
  gateway-js/CHANGELOG.md
  gateway-js/package.json
  harmonizer/Cargo.toml
  harmonizer/package.json
  internals-js/package.json
  package-lock.json
  query-graphs-js/CHANGELOG.md
  query-graphs-js/package.json
  query-planner-js/package.json
  router-bridge/package.json
  subgraph-js/package.json
Labels: :label: release

#1402 Use optional syntax to avoid array in call to buildSubgraphSchema
  docs/source/api/apollo-subgraph.mdx
  docs/source/quickstart-pt-3.mdx
  docs/source/subgraphs.mdx
Labels: ↪️ port-to-2.x

#1410 Docs: bump to gatsby v3
  docs/package-lock.json
  docs/package.json
Labels: ↪️ backport-to-0.x
