Repository apollographql/federation, pull requests merged in 2023-03, with the labels that each got.

#2406 Node 12 compatibility testing (version-0.x)
  .circleci/config.yml
  gateway-js/package.json
  gateway-js/src/__tests__/executeQueryPlan.test.ts
  gateway-js/src/__tests__/execution-utils.ts
  gateway-js/src/config.ts
  gateway-js/src/datasources/LocalGraphQLDataSource.ts
  gateway-js/src/datasources/RemoteGraphQLDataSource.ts
  gateway-js/src/datasources/__tests__/LocalGraphQLDataSource.test.ts
  gateway-js/src/datasources/__tests__/RemoteGraphQLDataSource.test.ts
  gateway-js/src/datasources/types.ts
  gateway-js/src/executeQueryPlan.ts
  gateway-js/src/index.ts
  gateway-js/src/supergraphManagers/IntrospectAndCompose/loadServicesFromRemoteEndpoint.ts
  gateway-js/src/typings/serverGatewayInterface.ts
  package-lock.json
  v12-node-compatibility/.npmrc
  v12-node-compatibility/package.json
Labels: P3

#2430 docs: expose metadata about federated subgraphs
  docs/source/building-supergraphs/supported-subgraphs.md
Labels: :memo: documentation

#2434 docs: update link imports to reference fed v2.3
  docs/source/entities-advanced.mdx
  docs/source/federated-types/federated-directives.mdx
  docs/source/federated-types/overview.mdx
  docs/source/federated-types/sharing-types.mdx
  docs/source/subgraph-spec.mdx
Labels: :memo: documentation

#2389 subscriptions support in the query planner
  .changeset/forty-hairs-flow.md
  .changeset/many-rats-allow.md
  composition-js/src/__tests__/compose.subscription.test.ts
  composition-js/src/merging/merge.ts
  federation-integration-testsuite-js/src/matchers/toCallService.ts
  gateway-js/src/executeQueryPlan.ts
  internals-js/src/definitions.ts
  query-planner-js/src/QueryPlan.ts
  query-planner-js/src/__tests__/buildPlan.interfaceObject.test.ts
  query-planner-js/src/__tests__/buildPlan.subscription.test.ts
  query-planner-js/src/__tests__/testHelper.ts
  query-planner-js/src/buildPlan.ts
  query-planner-js/src/snapshotSerializers/queryPlanSerializer.ts
Labels: status/needs-review

#2458 docs: update latest fed subgraph compatibility results
  docs/source/building-supergraphs/supported-subgraphs.md
Labels: :memo: documentation

#2387 Refactor selection set implementation to be immutable
  .changeset/curvy-balloons-flash.md
  composition-js/src/validate.ts
  gateway-js/src/executeQueryPlan.ts
  gateway-js/src/resultShaping.ts
  internals-js/package.json
  internals-js/src/__tests__/operations.test.ts
  internals-js/src/definitions.ts
  internals-js/src/federation.ts
  internals-js/src/operations.ts
  internals-js/src/precompute.ts
  internals-js/src/values.ts
  package-lock.json
  query-graphs-js/src/graphPath.ts
  query-graphs-js/src/querygraph.ts
  query-planner-js/src/buildPlan.ts
  query-planner-js/src/conditions.ts
Labels: status/needs-review

#2501 chore: update latest federation compatibility results
  docs/source/building-supergraphs/supported-subgraphs.md
Labels: :memo: documentation
