Repository apollographql/federation, pull requests merged in 2023-02, with the labels that each got.

#2401 docs: update latest subgraph compatibility results
  docs/source/building-supergraphs/supported-subgraphs.md
Labels: :memo: documentation

#2384 @apollo/gateway - Expose the current request query path to the "willSendRequest" and "didReceiveResponse" hooks
  .changeset/flat-books-sin.md
  gateway-js/src/datasources/RemoteGraphQLDataSource.ts
  gateway-js/src/datasources/types.ts
  gateway-js/src/executeQueryPlan.ts
Labels: status/needs-review

#2385 Add cache option to config to expose ApolloGateway's queryPlanStore
  .changeset/forty-gifts-burn.md
  gateway-js/package.json
  gateway-js/src/__tests__/gateway/endToEnd.test.ts
  gateway-js/src/index.ts
  package-lock.json
  query-planner-js/src/config.ts
  query-planner-js/src/index.ts
Labels: status/needs-review

#2416 Keep `next` tag up-to-date on publish
  .github/workflows/release.yml
  package-lock.json
  package.json
  scripts/update-next-tags.mjs
Labels: P2

#2310 Make queryPlanStoreKey a hash of both the query and Operation name
  .changeset/fluffy-toes-deliver.md
  gateway-js/src/index.ts
Labels: status/needs-review, P2
